[Fisch]
Control = 0.08

[Macro]
# Avaliable Options to apply:

#pulse-ms = 100
#hold-scale = 0.6
#deadzone-px = 8
#shake-min-pixels = 20
#steering = mouse
#exit-key = f8
#window-title = Sober

[Discord]
url = "insert_discord_webhook"
