[Fisch]
control = 0.08

[Macro]
<<<<<<< HEAD
# Avaliable Options to apply:

#pulse-ms = 100
#hold-scale = 0.6
#deadzone-px = 8
#shake-min-pixels = 20
#steering = mouse
#exit-key = f8
#window-title = Sober

[Discord]
url = "insert_discord_webhook"
=======
hold-scale = 0.2459
window-title = 
exit-key = f8
steering = mouse
pulse-ms = 
shake-min-pixels = 12
deadzone-px = 6

[Discord]
url = https://discord.com/api/webhooks/1540022539190014062/k25OdIAJweEXLRA9H_u-ZSenjtOBnPC2hvojZcwcwpMciM_I7pu-XDJGum0kvvvsQKsi

>>>>>>> b151d6f (Macro Release v1.12)
